### PR TITLE
chore: introduce testing utility dependency

### PR DESCRIPTION
**Pull request by KeranYang**

### CODE REVIEW

**Comment by chandankumar4** [comment]
@KeranYang I need to get this https://github.com/numaproj-contrib/aws-sqs-sink-go/pull/2 PR merged to fix the pipeline failure, after than I can verify this PR changes.

Probably I need to make some change related to deploying moto service, which was done from setup suite in my case. Also redis and e2e-pod is not required but this fixture will deploy that also as it won't harm but taking extra resource and time to run.

**Comment by KeranYang** [comment]
> redis and e2e-pod is not required

Agreed. I am keeping them for now just in case there is future use cases. Will monitor and see if maintaining them increases engineer efforts, if so I will remove them.

**Comment by chandankumar4** [comment]
If you can resolve the conflict, then we can merge this PR but e2e test will fail, I'll raise another PR to fix it?

**Comment by KeranYang** [comment]
@chandankumar4 on your next PR, could you remove the dependency on `github.com/numaproj/numaflow v0.11.0` ? Let's create our own logger from scratch. The rationale is that numaflow is not a library and UDSink should only depend on numaflow-go sdk.

**Pull request merged**
